"""empty message

Revision ID: 1c2c1b2a9a94
Revises: 4a9258eee70e
Create Date: 2021-09-12 09:40:37.743847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c2c1b2a9a94'
down_revision = '4a9258eee70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=32), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'wordbank')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wordbank', postgresql.ARRAY(sa.VARCHAR(length=64)), autoincrement=False, nullable=True))
    op.drop_table('words')
    # ### end Alembic commands ###
