"""empty message

Revision ID: 4a9258eee70e
Revises: c3abf3971249
Create Date: 2021-09-12 09:32:16.320127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a9258eee70e'
down_revision = 'c3abf3971249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wordbank', postgresql.ARRAY(sa.String(length=64)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wordbank')
    # ### end Alembic commands ###
