"""empty message

Revision ID: c3abf3971249
Revises: e40e7466a17f
Create Date: 2021-09-12 08:57:39.493835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3abf3971249'
down_revision = 'e40e7466a17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('stemmed_content', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'stemmed_content')
    # ### end Alembic commands ###
