"""empty message

Revision ID: e40e7466a17f
Revises: 10ab1ef18fb7
Create Date: 2021-09-11 20:28:00.469846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40e7466a17f'
down_revision = '10ab1ef18fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('language_code', sa.String(length=20), nullable=True))
    op.drop_column('posts', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('language', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('posts', 'language_code')
    # ### end Alembic commands ###
